CREATE TABLE IF NOT EXISTS `users` (
    `id` BIGINT UNSIGNED PRIMARY KEY,
    `email` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `nickname` VARCHAR(50) NOT NULL,
    `status` TINYINT UNSIGNED NOT NULL DEFAULT 0,
    `dateline` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `is_del` BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE(`email`)
) ENGINE=INNODB CHARSET=UTF8MB4 COLLATE=utf8mb4_unicode_ci;